# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x04\x63ore\"]\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x12\n\nupdated_at\x18\x05 \x01(\x03\"\x0f\n\rGetAllRequest\"\x1c\n\x0eGetByIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x11\x43reateItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"=\n\x11ListItemsResponse\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.core.Item\x12\r\n\x05total\x18\x02 \x01(\x03\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8b\x02\n\x0bItemService\x12\x36\n\x06GetAll\x12\x13.core.GetAllRequest\x1a\x17.core.ListItemsResponse\x12+\n\x07GetByID\x12\x14.core.GetByIDRequest\x1a\n.core.Item\x12-\n\x06\x43reate\x12\x17.core.CreateItemRequest\x1a\n.core.Item\x12\x33\n\x06\x44\x65lete\x12\x13.core.DeleteRequest\x1a\x14.core.DeleteResponse\x12\x33\n\x06Health\x12\x13.core.HealthRequest\x1a\x14.core.HealthResponseB\x10Z\x0e\x62\x61\x63kend/pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016backend/pkg/pb'
  _globals['_ITEM']._serialized_start=20
  _globals['_ITEM']._serialized_end=113
  _globals['_GETALLREQUEST']._serialized_start=115
  _globals['_GETALLREQUEST']._serialized_end=130
  _globals['_GETBYIDREQUEST']._serialized_start=132
  _globals['_GETBYIDREQUEST']._serialized_end=160
  _globals['_CREATEITEMREQUEST']._serialized_start=162
  _globals['_CREATEITEMREQUEST']._serialized_end=216
  _globals['_LISTITEMSRESPONSE']._serialized_start=218
  _globals['_LISTITEMSRESPONSE']._serialized_end=279
  _globals['_DELETEREQUEST']._serialized_start=281
  _globals['_DELETEREQUEST']._serialized_end=308
  _globals['_DELETERESPONSE']._serialized_start=310
  _globals['_DELETERESPONSE']._serialized_end=343
  _globals['_HEALTHREQUEST']._serialized_start=345
  _globals['_HEALTHREQUEST']._serialized_end=360
  _globals['_HEALTHRESPONSE']._serialized_start=362
  _globals['_HEALTHRESPONSE']._serialized_end=394
  _globals['_ITEMSERVICE']._serialized_start=397
  _globals['_ITEMSERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
