# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x04\x63ore\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rGreetResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2A\n\rOrdersService\x12\x30\n\x05Greet\x12\x12.core.GreetRequest\x1a\x13.core.GreetResponseB\x10Z\x0e\x62\x61\x63kend/pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016backend/pkg/pb'
  _globals['_GREETREQUEST']._serialized_start=22
  _globals['_GREETREQUEST']._serialized_end=50
  _globals['_GREETRESPONSE']._serialized_start=52
  _globals['_GREETRESPONSE']._serialized_end=85
  _globals['_ORDERSSERVICE']._serialized_start=87
  _globals['_ORDERSSERVICE']._serialized_end=152
# @@protoc_insertion_point(module_scope)
