{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ .service }}-ingress
  namespace: {{ $.Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- toYaml $.Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .paths[0].path }}
            pathType: {{ .paths[0].pathType }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .paths[0].port }}
{{- end }}
{{- end }}
