apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ${K8S_NAMESPACE}
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: ${GATEWAY_PORT}
      protocol: TCP
      name: http
  selector:
    app: gateway
