apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: microservices
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: microservices
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: "gateway-secret"
